# Travis-CI Build for the OpenRA website
# see travis-ci.org for details

language: ruby
rvm:
  - 2.0

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

env:
  global:
    secure: "Ot/NHtOO6W2pGcWAvXpdz3tKoppcvyZ3XlbPNMr/qOlRhcySMPB5wgkdZJFS3D+E5QoXeB+aOYuAW4dqm5R2bnwCoAnbgMrLItN6nejQ/CR5gejEHLrugoM5hXp0BuY/MUiRMkhj9ERMDIbwUulC2Zpsmx05Wq4q7+ZRBF451rE="
    secure: "I1py0ajtKd71kkD3mB/bORU/Tg6DqclQVd7iObhaFcM7YqWb8hKWjjTWuVO2WhUxskRiMyNqxTL+6+VCcHz1fW0Q2EjP627a4o7vXCLXROZkRJ+Y+uuSnL/5SaW0EytC09sDbNwa0qUll3QdkQSuBJ+r6d9PwG+MicT+4C4CyA0="

install:

script:
 - nanoc compile

after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./update-github-pages.sh

# Only watch the production branch.
branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
